trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_and_deploy
    displayName: Build and Deploy
    jobs:
      - job: build_and_deploy
        container: maven:3-eclipse-temurin-21
        displayName: Build Fractal Cloud Demo
        steps:
          - task: MavenAuthenticate@0
            displayName: Authenticate to Fractal SDK Package Repo
            inputs:
              artifactsFeeds: migration-poc-v1
              mavenServiceConnections: yw-fractal-java-sdk
          - task: Maven@3
            displayName: Maven Build
            inputs:
              mavenPomFile: pom.xml
              javaHomeSelection: 'path'
              jdkDirectory: '/opt/java/openjdk'
              goals: clean deploy
