rootProject.name = "fractal-samples"
include(":azure.appservice.sample")
include(":azure.storage.account.sample")
include(":aws.elastic.datastore.sample")
include(":oci.prometheus.ambassador.sample")
include(":azure.prometheus.ambassador.sample")
include(":azure")
include(":gcp.prometheus.sample")
include(":aws.eks.ambassador.sample")
include(":azure.custom.workload.sample")
include(":environment-initialization")
include(":azure.appservice.dotnet.sample")
include(":gcp.custom.workload.sample")
include(":aws.eks.full.sample")
include(":aws")
include(":azure.multiple.resources.sample")
include(":azure.cosmos.sample")
include(":oci.oke.full.sample")
include(":aws.shared.config")
include(":azure.postgresql.sample")
include(":azure.relay.sample")
include(":azure.aks.full.sample")
include(":azure.aks.ambassador.sample")
include(":oci.elastic.logging.sample")
include(":oci.oke.ambassador.sample")
include(":azure.aks.minimum.sample")
include(":migration.infrastructure")
include(":oci.shared.config")
include(":elastic-logging-ambassador-sample")
include(":aws.eks.minimum.sample")
include(":gcp.shared.config")
include(":oci.elastic.datastore.sample")
include(":aws.custom.workload.sample")
include(":azure.elastic.logging.ambassador.sample")
include(":oci.oke.minimum.sample")
include(":gcp")
include(":azure.service.bus.full.sample")
include(":oci.custom.workload.sample")
include(":aws.elastic.logging.ambassador.sample")
include(":azure.shared.config")
include(":aws.prometheus.ambassador.sample")
include(":azure.elastic.datastore.sample")
include(":azure.service.bus.minimum.sample")
include(":oci.elastic.logging.ambassador.sample")
include(":azure.cdn.sample")
include(":gcp.ambassador.sample")
include(":gcp.gke.minimum.sample")
include(":aws.elastic.logging.sample")
include(":azure.elastic.logging.sample")
include(":oci")
include(":gcp.elastic.logging.sample")
include(":migration.architecture")
include(":gcp.elastic.datastore.sample")
include(":gcp.gke.full.sample")
include(":gcp.postgresql.sample")

project(":azure.appservice.sample").projectDir = file("livesystem-first/azure/appservice-sample")
project(":azure.storage.account.sample").projectDir = file("livesystem-first/azure/storage-account-sample")
project(":aws.elastic.datastore.sample").projectDir = file("livesystem-first/aws/elastic-datastore-sample")
project(":oci.prometheus.ambassador.sample").projectDir = file("livesystem-first/oci/prometheus-ambassador-sample")
project(":azure.prometheus.ambassador.sample").projectDir = file("livesystem-first/azure/prometheus-ambassador-sample")
project(":gcp.prometheus.sample").projectDir = file("livesystem-first/gcp/prometheus-ambassador-sample")
project(":aws.eks.ambassador.sample").projectDir = file("livesystem-first/aws/ambassador-sample")
project(":azure.custom.workload.sample").projectDir = file("livesystem-first/azure/custom-workload-sample")
project(":azure.appservice.dotnet.sample").projectDir = file("livesystem-first/azure/appservice-dotnet-sample")
project(":gcp.custom.workload.sample").projectDir = file("livesystem-first/gcp/custom-workload-sample")
project(":aws.eks.full.sample").projectDir = file("livesystem-first/aws/eks-full-sample")
project(":azure.multiple.resources.sample").projectDir = file("livesystem-first/azure/azure-multiple-resources-sample")
project(":azure.cosmos.sample").projectDir = file("livesystem-first/azure/cosmos-sample")
project(":oci.oke.full.sample").projectDir = file("livesystem-first/oci/oke-full-sample")
project(":aws.shared.config").projectDir = file("livesystem-first/aws/shared-config")
project(":azure.postgresql.sample").projectDir = file("livesystem-first/azure/postgresql-sample")
project(":azure.relay.sample").projectDir = file("livesystem-first/azure/relay-sample")
project(":azure.aks.full.sample").projectDir = file("livesystem-first/azure/aks-full-sample")
project(":azure.aks.ambassador.sample").projectDir = file("livesystem-first/azure/ambassador-sample")
project(":oci.elastic.logging.sample").projectDir = file("livesystem-first/oci/elastic-logging-sample")
project(":oci.oke.ambassador.sample").projectDir = file("livesystem-first/oci/ambassador-sample")
project(":azure.aks.minimum.sample").projectDir = file("livesystem-first/azure/aks-minimum-sample")
project(":migration.infrastructure").projectDir = file("fractal-first/infrastructure")
project(":oci.shared.config").projectDir = file("livesystem-first/oci/shared-config")
project(":elastic-logging-ambassador-sample").projectDir = file("livesystem-first/gcp/elastic-logging-ambassador-sample")
project(":aws.eks.minimum.sample").projectDir = file("livesystem-first/aws/eks-minimum-sample")
project(":gcp.shared.config").projectDir = file("livesystem-first/gcp/shared-config")
project(":oci.elastic.datastore.sample").projectDir = file("livesystem-first/oci/elastic-datastore-sample")
project(":aws.custom.workload.sample").projectDir = file("livesystem-first/aws/custom-workload-sample")
project(":azure.elastic.logging.ambassador.sample").projectDir = file("livesystem-first/azure/elastic-logging-ambassador-sample")
project(":oci.oke.minimum.sample").projectDir = file("livesystem-first/oci/oke-minimum-sample")
project(":azure.service.bus.full.sample").projectDir = file("livesystem-first/azure/service-bus-full-sample")
project(":oci.custom.workload.sample").projectDir = file("livesystem-first/oci/custom-workload-sample")
project(":aws.elastic.logging.ambassador.sample").projectDir = file("livesystem-first/aws/elastic-logging-ambassador-sample")
project(":azure.shared.config").projectDir = file("livesystem-first/azure/shared-config")
project(":aws.prometheus.ambassador.sample").projectDir = file("livesystem-first/aws/prometheus-ambassador-sample")
project(":azure.elastic.datastore.sample").projectDir = file("livesystem-first/azure/elastic-datastore-sample")
project(":azure.service.bus.minimum.sample").projectDir = file("livesystem-first/azure/service-bus-minimum-sample")
project(":oci.elastic.logging.ambassador.sample").projectDir = file("livesystem-first/oci/elastic-logging-ambassador-sample")
project(":azure.cdn.sample").projectDir = file("livesystem-first/azure/azure-cdn-sample")
project(":gcp.ambassador.sample").projectDir = file("livesystem-first/gcp/ambassador-sample")
project(":gcp.gke.minimum.sample").projectDir = file("livesystem-first/gcp/gke-minimum-sample")
project(":aws.elastic.logging.sample").projectDir = file("livesystem-first/aws/elastic-logging-sample")
project(":azure.elastic.logging.sample").projectDir = file("livesystem-first/azure/elastic-logging-sample")
project(":gcp.elastic.logging.sample").projectDir = file("livesystem-first/gcp/elastic-logging-sample")
project(":migration.architecture").projectDir = file("fractal-first/architecture")
project(":gcp.elastic.datastore.sample").projectDir = file("livesystem-first/gcp/elastic-datastore-sample")
project(":gcp.gke.full.sample").projectDir = file("livesystem-first/gcp/gke-full-sample")
project(":gcp.postgresql.sample").projectDir = file("livesystem-first/gcp/postgresql-sample")
