openapi: 3.0.0
info:
  title: City Information API for Remote Workers
  description: This API provides detailed information about cities worldwide, focusing on data useful for remote workers deciding on their next destination.
  version: "1.0.0"
  contact:
    name: API Support
    url: http://example.com/support
    email: support@example.com
servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /cities:
    get:
      summary: List cities
      description: Retrieve a list of cities that have detailed information available.
      operationId: listCities
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
          description: Limit the number of cities returned.
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          description: Offset in the city list.
      responses:
        '200':
          description: A list of cities
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Total number of cities available.
                  cities:
                    type: array
                    items:
                      $ref: '#/components/schemas/City'
        '400':
          description: Invalid parameters supplied

  /cities/{cityId}:
    get:
      summary: Get city details
      description: Retrieves detailed information about a specific city, useful for remote workers.
      operationId: getCityDetails
      parameters:
        - in: path
          name: cityId
          required: true
          schema:
            type: string
          description: The ID of the city to retrieve details for.
      responses:
        '200':
          description: Detailed information about a city
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CityDetail'
        '404':
          description: City not found

components:
  schemas:
    City:
      type: object
      properties:
        cityId:
          type: string
          description: Unique identifier for the city.
        name:
          type: string
          description: Name of the city.
        country:
          type: string
          description: Country where the city is located.

    CityDetail:
      type: object
      properties:
        cityId:
          type: string
        name:
          type: string
        country:
          type: string
        costOfLivingIndex:
          type: number
          format: double
          description: A normalized index of the overall cost of living.
        internetSpeed:
          type: object
          properties:
            download:
              type: number
              description: Average download speed in Mbps.
            upload:
              type: number
              description: Average upload speed in Mbps.
        coworkingSpaces:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              address:
                type: string
              rating:
                type: number
                format: double
        safetyIndex:
          type: number
          format: double
          description: Safety index based on local crime rates, safety, and security services.
        climate:
          type: object
          properties:
            averageTemperature:
              type: number
              description: Average yearly temperature in Celsius.
            rainfall:
              type: number
              description: Average yearly rainfall in mm.
