apiVersion: v1
kind: Namespace
metadata:
  name: migration-poc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: migration-poc
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8080
    name: http
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: migration-poc
  labels:
    app: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: crfractalscaitestv1.azurecr.io/migration-backend:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
