name: Build and run LiveSystem for Fractal Cloud

on:
  pull_request:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Maven Build 
        run: mvn clean compile assembly:single
        #working-directory: ./fractal.sdk
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven Deploy
        run: java -jar target/sdk-sample-jar-with-dependencies.jar
        env:
          SECRET: ${{ secrets.SECRET }}
    