trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build SDK Sample Fractal
    steps:
    - task: MavenAuthenticate@0
      displayName: Authenticate to YanchWare Package Repo
      inputs:
        MavenServiceConnections: yanchware
    - task: CmdLine@2
      displayName: Maven Build
      inputs:
        script: |
          mvn clean compile assembly:single
    - publish: 'target/sdk-sample-jar-with-dependencies.jar'
      artifact: Fractal

- stage: test_deploy
  dependsOn: build
  displayName: Deploy to Test
  jobs:
  - template: 'azure-pipelines.deployment.yml'
    parameters:
      environment: SdkSample-Test
- stage: prod_deploy
  condition: eq(variables['Build.Reason'], 'Manual')
  dependsOn: test_deploy
  displayName: Deploy to Production
  jobs:
  - template: 'azure-pipelines.deployment.yml'
    parameters:
      environment: SdkSample-Production
