name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.10.2

      - name: Restore dependencies cache
        uses: actions/cache@v4
        id: cache-restore
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: fractal-sdk-dependencies

      - name: Build with Gradle
        run: ./gradlew clean test

      - name: Save dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: fractal-sdk-dependencies